export const fillHomeIcon = document.createElement("img")
fillHomeIcon.src = `/svgs/header-footer/fillHome.svg`
fillHomeIcon.alt = "homeIcon"
export const homeIcon = document.createElement("img")
homeIcon.src = "/svgs/header-footer/home.svg"
homeIcon.alt = "homeIcon"
export const cartIcon = document.createElement("img")
cartIcon.src = `/svgs/header-footer/cart.svg`
cartIcon.alt = "cartIcon"
export const fillCartIcon = document.createElement("img")
fillCartIcon.src = `/svgs/header-footer/CartFill.svg`
fillCartIcon.alt = "cartIcon"

export const cartIconBorderWhite = document.createElement("img")
cartIconBorderWhite.src = `/svgs/product/orderBorderWhite.svg`
cartIconBorderWhite.alt = "cartIcon"

export const orderIcon = document.createElement("img")
orderIcon.src = `/svgs/header-footer/orders.svg`
orderIcon.alt = "orderIcon"
export const walletIcon = document.createElement("img")
walletIcon.src = `/svgs/header-footer/wallet.svg`
walletIcon.alt = "walletIcon"
export const profileIcon = document.createElement("img")
profileIcon.src = `/svgs/header-footer/profile.svg`
profileIcon.alt = "profileIcon"
export const slide1Image = document.createElement("img")
slide1Image.src = "/svgs/slide/slide1.svg";
slide1Image.alt = "slide1 shoes image";
export const slide2Image = document.createElement("img")
slide2Image.src = "/svgs/slide/slide2.svg"
slide2Image.alt = "slide2 shoes image"
export const slide3Image = document.createElement("img")
slide3Image.src = "/svgs/slide/slide3.svg"
slide3Image.alt = "slide3 shoes image"
export const slider1 = document.createElement("img")
slider1.src = "/svgs/slide/slider1.svg";
export const slider2 = document.createElement("img")
slider2.src = "/svgs/slide/slider2.svg";
export const slider3 = document.createElement("img")
slider3.src = "/svgs/slide/slider3.svg";
